version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - bump:patch
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - bump:patch
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
